### ISSUE TITLE
The plan™

### ISSUE THREAD

**Issue by gr2m** [octokit/app-permissions#1]
follow up https://mobile.twitter.com/rarkins/status/1295306432812810241 /ping @rarkins 

Here is what I think this could work, everything is up for discussion

1. Scrape the [Permissions required for GitHub Apps](https://docs.github.com/en/rest/reference/permissions-required-for-github-apps) documentation page on a daily basis using GitHub Actions
2. Cache the HTML in a file in the repository for easier debugability
3. Turn the HTML to a JSON format using [`cheerio`](https://github.com/cheeriojs/cheerio#readme). Turn the descriptions into markdown using [`turndown`](https://github.com/domchristie/turndown)
4. If there is a change, create a pull request
5. Upon merge, automatically publish a new version to npm (`@octokit/app-permissions`)

The JSON output could look something like this, e.g. for the [`issues` permission](https://docs.github.com/en/rest/reference/permissions-required-for-github-apps#permission-on-issues):

```js
{
  // ...
  "issues": {
    "description": "Issues and pull requests are closely related. For more information, see \"[List issues assigned to the authenticated user](https://docs.github.com/en/rest/reference/issues#list-issues-assigned-to-the-authenticated-user). If your GitHub App has ...\"",
    "access-by-path": {
      "GET /repos/{owner}/{repo}/issues": "read",
      "POST /repos/{owner}/{repo}/issues": "write",
      // ...
    }
  },
  // ...
}
```

Once we have that working, we could work on

1. Add versions for GHES versions
2. Upload the resulting JSON files as artefacts to GitHub releases
3. Setup a release notifier for people who want to consume the JSON file but are not working with JS, compare https://github.com/apps/openapi-release-notifier

**Comment by travi** [comment]
> Turn the HTML to a JSON format using cheerio. Turn the descriptions into markdown using turndown

i've enjoyed working with [rehype](https://github.com/rehypejs/rehype) and [remark](https://github.com/remarkjs/remark) for working with html and markdown as ASTs and converting between the two. thought i'd just mention in case they can be helpful in this effort

**Comment by gr2m** [comment]
I wonder if we would also need the reverse map: `route` -> `permission`. It's easy to do programmatically, but if there are common use cases for both, we could as well create both at build time

What's your use case @rarkins?

**Comment by rarkins** [comment]
My use case was twofold:
- Document for users which endpoints we access and therefore which permissions are requested
- (maybe) Introduce some type of static check that cross-references our API calls against such a list to make sure it's current

**Comment by gr2m** [comment]
Sounds like the mapping of route to permissions might be more useful to you?
