### ISSUE TITLE
Octokit Bot automated PR's are not being labeled with `maintainance` label

### ISSUE THREAD

**Issue by oscard0m** [octokit/app-permissions#37]
**What happened?**
Octokit Bot automated PR's are not being labeled with `maintainance` label

i.e. https://github.com/octokit/app-permissions/pull/34

**What did you expect to happen?**
After this change (https://github.com/octokit/app-permissions/commit/fe8fc69895e914af50b2992425d8783a118c8fd8), automated PR's opened by Octokit Bot should be labeled with `maintainance` label, but they are not.
 
**What the problem might be**
For what I see in the logs of the GitHub Action, looks like the app does not have permissions on this repository for updating labels. Could be that?

https://github.com/octokit/app-permissions/runs/1713277148?check_suite_focus=true

**Comment by gr2m** [comment]
We use a personal access token by @octokitbot for creating the pull request (I actually don't recall why we don't use `secrets.GITHUB_TOKEN` ...). But I didn't add @octokitbot to this repository. I did that now, this should be good to go

**Comment by gr2m** [comment]
jap: https://github.com/octokit/app-permissions/pull/48
